NETWORK_PASSPHRASE="Public Global Stellar Network ; April 2024"
ACCOUNTS=["GDDWFPST4EELD5VYKJ3E7VM7U6CNHUV7JXW6I74YJY5LWMYJKPVXER4O","GBGIQCRTAG3JT6PAB26725FVRLGD2NX2J7PIOUKKVA5BTMDKD3GSCRIO"]
SIGNING_KEY="GDDWFPST4EELD5VYKJ3E7VM7U6CNHUV7JXW6I74YJY5LWMYJKPVXER4O"
WEB_AUTH_ENDPOINT=""
TRANSFER_SERVER_SEP0024=""

[DOCUMENTATION]
ORG_NAME=""
ORG_DBA=""
ORG_URL=""
ORG_LOGO=""
ORG_DESCRIPTION=""
ORG_PHYSICAL_ADDRESS=""
ORG_OFFICIAL_EMAIL=""
ORG_TWITTER=""
ORG_GITHUB=""
ORG_SUPPORT_EMAIL=""

[[PRINCIPALS]]
name=""
email=""

[[CURRENCIES]]
code="USD"
issuer="GBGIQCRTAG3JT6PAB26725FVRLGD2NX2J7PIOUKKVA5BTMDKD3GSCRIO"
name="USD"
desc="The official currency of the United States of America"
display_decimals=2
is_asset_anchored=true
is_unlimited=true
anchor_asset_type="fiat"
anchor_asset="USD"
redemption_instructions="Access through trusted partners and stellar wallets"
status="live"
image="https://ipfs.io/ipfs/bafkreibpzncuhbk5ozhdw7xkcdoyf3xhwhcwcf6sj7axjzimxw6vm6pvyy"

[[CURRENCIES]]
code="EURO"
issuer="GBGIQCRTAG3JT6PAB26725FVRLGD2NX2J7PIOUKKVA5BTMDKD3GSCRIO"
name="EURO"
desc="Monetary unit and currency of the European Union"
display_decimals=2
is_asset_anchored=true
is_unlimited=true
anchor_asset_type="fiat"
anchor_asset="EURO"
redemption_instructions="Access through trusted partners and stellar wallets"
status="live"
image="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_Wd0DLe0ioB0c2pIJXg0IB9l9J2cXtsrQ6dlqshJCww&s"

[[CURRENCIES]]
code="GBP"
issuer="GBGIQCRTAG3JT6PAB26725FVRLGD2NX2J7PIOUKKVA5BTMDKD3GSCRIO"
name="GBP"
desc="British pound sterling, the official currency of the United Kingdom and its territories"
display_decimals=2
is_asset_anchored=true
is_unlimited=true
anchor_asset_type="fiat"
anchor_asset="GBP"
redemption_instructions="Access through trusted partners and stellar wallets"
status="live"
image="https://ipfs.io/ipfs/bafkreiec6ybohsdv2jzln2lzcz36n2gju2gkcdfowz4vuqqmzqg6ah6efe"

[[CURRENCIES]]
code="SEK"
issuer="GBGIQCRTAG3JT6PAB26725FVRLGD2NX2J7PIOUKKVA5BTMDKD3GSCRIO"
name="SEK"
desc="Currency code for the Swedish krona, which has been Sweden's currency since 1873"
display_decimals=2
is_asset_anchored=true
is_unlimited=true
anchor_asset_type="fiat"
anchor_asset="SEK"
redemption_instructions="Access through trusted partners and stellar wallets"
status="live"
image="https://www.xe.com/svgs/flags/sek.static.svg"

[[CURRENCIES]]
code="CAD"
issuer="GBGIQCRTAG3JT6PAB26725FVRLGD2NX2J7PIOUKKVA5BTMDKD3GSCRIO"
name="CAD"
desc="Official currency of Canada which is also abbreviated as CAD in the international currency exchange markets"
display_decimals=2
is_asset_anchored=true
is_unlimited=true
anchor_asset_type="fiat"
anchor_asset="CAD"
redemption_instructions="Access through trusted partners and stellar wallets"
status="live"
image="https://www.xe.com/svgs/flags/cad.static.svg"